version: "3"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  mangodb1:
    image: mongo
    #command: --serviceExecutor adaptive
    environment:
      - MONGO_INITDB_DATABASE=mangodb2
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  mangodb2:
    image: mongo
    #command: --serviceExecutor adaptive
    environment:
      - MONGO_INITDB_DATABASE=mangodb2
      - MONGO_INITDB_ROOT_USERNAME=${MANGO2_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MANGO2_INITDB_ROOT_PASSWORD}

  products:
    build: .
    #command: python manage.py runserver 0.0.0.0:8000
    command: bash /code/deploy/products_service_api.sh
    volumes:
      - .:/code
    ports:
      - "8000:80"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TAX_CALC_API_URL=http://tax-calculator/
      - GIPHY_API_URL=https://api.giphy.com/v1/
      - GIPHY_API_KEY=${GIPHY_API_KEY}
    depends_on:
      - db

  products-csv-exporter:
    build: .
    command: bash /code/deploy/products_csv_exporter.sh
    volumes:
      - .:/code
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SFTP_HOST=sftp
      - SFTP_USERNAME=${SFTP_USERNAME}
      - SFTP_PASSWORD=${SFTP_PASSWORD}
    depends_on:
      - db
      - sftp

  products-csv-importer:
    build: .
    command: bash /code/deploy/products_csv_importer.sh
    volumes:
      - .:/code
    environment:
      - SFTP_HOST=sftp
      - SFTP_USERNAME=${SFTP_USERNAME}
      - SFTP_PASSWORD=${SFTP_PASSWORD}
      - MANGODB2_HOST=mangodb2
      - MANGODB2_USERNAME=${MANGO2_INITDB_ROOT_USERNAME}
      - MANGODB2_PASSWORD=${MANGO2_INITDB_ROOT_PASSWORD}
    depends_on:
      - sftp
      - mangodb2

  sftp:
    image: atmoz/sftp
    volumes:
      - ./upload:/home/csvworker/upload
    ports:
      - "2222:22"
    command: ${SFTP_USERNAME}:${SFTP_PASSWORD}:1001

  tax-calculator:
    build: .
    command: bash /code/deploy/tax_calc_api.sh
    volumes:
      - .:/code
    ports:
      - "8001:80"


