openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /mwst/:
    get:
      operationId: listtax_calcs
      description: ''
      parameters: []
      responses:
        '200':
          content:
            text/html:
              schema:
                type: array
                items: {}
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - mwst
