# Generated by Django 3.2.8 on 2021-11-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=20)),
                ('location', models.TextField()),
                ('material', models.CharField(max_length=100)),
                ('timesofuse', models.CharField(max_length=100)),
                ('brand', models.TextField()),
                ('slogan', models.TextField()),
                ('recycling', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
            ],
        ),
    ]
